"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import type { FooterData, SiteSettings } from "../lib/types";

export function SiteFooter({data,settings}:{data:FooterData;settings:SiteSettings}){
  const name=settings.websiteName||"Bargain MOM";const logo=settings.logo||"/brand/bargain-mom-logo.png";const [status,setStatus]=useState("");
  async function subscribe(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setStatus("Sending…");try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api"}/newsletter`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});setStatus(r.ok?"You’re subscribed!":"Please try again.");if(r.ok)event.currentTarget.reset()}catch{setStatus("Please try again.")}}
  return <footer><div className="footer-main"><div className="footer-brand"><Link className="brand brand-logo footer-logo" href="/" aria-label={`${name} home`}><img src={logo} alt={name}/></Link><p>{data.description||settings.footerDescription}</p>{data.socialLinks?.length?<div className="social-links">{data.socialLinks.map(x=><a href={x.url} key={x.id} aria-label={x.label}>{x.label.slice(0,1)}</a>)}</div>:null}</div>{data.columns?.map(col=><div className="footer-column" key={col.id}><h4>{col.title}</h4>{col.links?.map(link=><Link key={link.id} href={link.url}>{link.label}</Link>)}</div>)}<div className="newsletter"><h4>{settings.newsletterTitle||"Newsletter"}</h4><p>{data.newsletterText||settings.newsletterText}</p><form onSubmit={subscribe}><input name="email" type="email" required placeholder="Enter your email"/><button>Subscribe</button></form>{status&&<small aria-live="polite">{status}</small>}</div></div><div className="footer-bottom"><span>{data.copyrightText||settings.copyright||`© ${new Date().getFullYear()} ${name}`}</span><div>{data.legalLinks?.map(link=><Link href={link.url} key={link.id}>{link.label}</Link>)}</div></div></footer>
}
