"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import type { FooterData, SiteSettings } from "../lib/types";
import { SafeImage } from "./SafeImage";

type AnalyticsWindow=Window&{dataLayer?:Record<string,unknown>[];__bargainMomDirectGa?:boolean;gtag?:(command:string,event:string,values:Record<string,unknown>)=>void};
type SocialPlatform="x"|"facebook"|"pinterest"|"telegram"|"instagram"|"tiktok";
type SocialLink={platform:SocialPlatform;label:string;url:string};
const socialMeta:Record<SocialPlatform,{label:string}>={x:{label:"X"},facebook:{label:"Facebook"},pinterest:{label:"Pinterest"},telegram:{label:"Telegram"},instagram:{label:"Instagram"},tiktok:{label:"TikTok"}};
function socialLinks(value:SiteSettings["socialMedia"]):SocialLink[]{if(!value||typeof value!=="object"||Array.isArray(value))return [];return (["instagram","facebook","tiktok","telegram","pinterest","x"] as SocialPlatform[]).flatMap(platform=>{const url=value[platform];return typeof url==="string"&&url.startsWith("https://")?[{platform,label:socialMeta[platform].label,url}]:[]})}
function SocialIcon({platform}:{platform:SocialPlatform}){if(platform==="instagram")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.35" cy="6.65" r="1" className="social-fill"/></svg>;if(platform==="facebook")return <svg viewBox="0 0 24 24" aria-hidden="true" className="social-facebook-icon"><path className="social-fill" d="M13.9 21v-8h2.7l.4-3h-3.1V8.1c0-.9.3-1.6 1.7-1.6H17V3.8c-.4-.1-1.3-.2-2.3-.2-2.3 0-3.8 1.4-3.8 4V10H8.3v3h2.6v8h3Z"/></svg>;if(platform==="tiktok")return <svg viewBox="0 0 24 24" aria-hidden="true"><path className="social-fill" d="M15 3c.4 2.3 1.6 3.7 4 4.1v3.1a8.5 8.5 0 0 1-4-1.2v6.2a5.9 5.9 0 1 1-5.9-5.9c.4 0 .8 0 1.2.1v3.1a2.8 2.8 0 1 0 1.6 2.6V3H15Z"/></svg>;if(platform==="telegram")return <svg viewBox="0 0 24 24" aria-hidden="true"><path className="social-fill" d="M21.5 4.2 18.6 20c-.2 1.1-1 1.4-1.8.9l-5.1-3.7-2.5 2.4c-.3.3-.5.5-1 .5l.4-5.2L18 6.5c.4-.4-.1-.6-.6-.3L6 13.4l-5-1.6c-1.1-.4-1.1-1.1.2-1.6L20 3c.9-.3 1.7.2 1.5 1.2Z"/></svg>;if(platform==="pinterest")return <svg viewBox="0 0 24 24" aria-hidden="true"><path className="social-fill" d="M12 3.2a8.8 8.8 0 0 0-3.2 17c-.1-1.4 0-3 .4-4.3l1.1-4.5s-.3-.6-.3-1.5c0-1.4.8-2.5 1.9-2.5.9 0 1.3.7 1.3 1.5 0 .9-.6 2.3-.9 3.5-.3 1 .5 1.9 1.5 1.9 1.8 0 3.2-1.9 3.2-4.6 0-2.4-1.7-4-4.2-4-2.9 0-4.6 2.2-4.6 4.4 0 .9.3 1.8.8 2.3.1.1.1.2.1.4l-.3 1.2c-.1.4-.3.5-.6.4-2.1-1-3.1-3.4-3.1-5.5 0-4.5 3.3-8.6 9.4-8.6 5 0 8.8 3.5 8.8 8.2 0 4.9-3.1 8.9-7.3 8.9-1.4 0-2.8-.7-3.2-1.6l-.9 3.3c-.3 1.3-1.2 2.9-1.8 3.9.7.2 1.4.3 2.1.3a8.8 8.8 0 0 0 0-17.6Z"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true" className="social-x-icon"><path className="social-fill" d="M18.9 2.8h2.8l-6.1 7 7.2 11.4h-5.6l-4.4-6.8-5.9 6.8H4.1l6.5-7.5L3.7 2.8h5.7l4 6.2 5.5-6.2Zm-1 16.7h1.5L8.6 4.4H7l10.9 15.1Z"/></svg>}
export function SiteFooter({data,settings}:{data:FooterData;settings:SiteSettings}){
  const name=settings.websiteName||"Bargain MOM";const logo=settings.logo||"/brand/bargain-mom-logo.webp";const [status,setStatus]=useState("");
  async function subscribe(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setStatus("Sending…");try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api"}/newsletter`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});setStatus(r.ok?"You’re subscribed!":"Please try again.");if(r.ok){element.reset();const values={page_path:location.pathname};const analytics=window as AnalyticsWindow;analytics.dataLayer=analytics.dataLayer||[];analytics.dataLayer.push({event:"newsletter_signup",...values});if(analytics.__bargainMomDirectGa&&typeof analytics.gtag==="function")analytics.gtag("event","newsletter_signup",values)}}catch{setStatus("Please try again.")}}
  const links=socialLinks(settings.socialMedia);
  return <footer><div className="footer-main"><div className="footer-brand"><Link className="brand brand-logo footer-logo" href="/" aria-label={`${name} home`}><SafeImage src={logo} alt={`${name} logo`} width={190} height={80} sizes="190px"/></Link><p>{data.description||settings.footerDescription}</p>{links.length?<nav className="social-links" aria-label="Follow Bargain MOM">{links.map(link=><a href={link.url} key={link.platform} aria-label={`Follow Bargain MOM on ${link.label}`} target="_blank" rel="noopener noreferrer"><SocialIcon platform={link.platform}/></a>)}</nav>:null}</div>{data.columns?.map(col=><div className="footer-column" key={col.id}><h4>{col.title}</h4>{col.links?.map(link=><Link key={link.id} href={link.url}>{link.label}</Link>)}</div>)}<div className="newsletter"><h4>{settings.newsletterTitle||"Newsletter"}</h4><p>{data.newsletterText||settings.newsletterText}</p><form onSubmit={subscribe}><input name="email" type="email" required placeholder="Enter your email"/><button>Subscribe</button></form>{status&&<small aria-live="polite">{status}</small>}</div></div><div className="footer-bottom"><span>{data.copyrightText||settings.copyright||`© ${new Date().getFullYear()} ${name}`}</span><div>{data.legalLinks?.map(link=><Link href={link.url} key={link.id}>{link.label}</Link>)}</div></div></footer>
}
