import assert from "node:assert/strict";
const base=process.env.API_TEST_URL||"http://localhost:4000/api";let cookie="";
async function request(path,method="GET",body){const response=await fetch(`${base}${path}`,{method,headers:{...(body instanceof FormData?{}:{"content-type":"application/json"}),...(cookie?{cookie}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const setCookie=response.headers.get("set-cookie");if(setCookie)cookie=setCookie.split(";")[0];const payload=response.status===204?null:await response.json();if(!response.ok)throw new Error(`${method} ${path} -> ${response.status}: ${JSON.stringify(payload)}`);return payload?.data??payload}
const created=[];
const login=await request("/auth/login","POST",{email:"admin@example.com",password:"LocalTestPass123"});assert.equal(login.admin.email,"admin@example.com");

const store=await request("/admin/stores","POST",{name:"CRUD Test Store",slug:"crud-test-store",description:"Temporary verification record",websiteUrl:"https://example.com",affiliateBaseUrl:"https://example.com/go",color:"#ff5a0a",active:true});created.push(["stores",store.id]);
const category=await request("/admin/categories","POST",{name:"CRUD Test Category",slug:"crud-test-category",description:"Temporary verification record",sortOrder:99,status:"ACTIVE"});created.push(["categories",category.id]);
const brand=await request("/admin/brands","POST",{name:"CRUD Test Brand",slug:"crud-test-brand",description:"Temporary verification record",active:true});created.push(["brands",brand.id]);
const options=await request("/admin/options");assert(options.stores.some(x=>x.id===store.id));assert(options.categories.some(x=>x.id===category.id));assert(options.brands.some(x=>x.id===brand.id));
let product=await request("/admin/products","POST",{title:"CRUD Test Product",slug:"crud-test-product",description:"Temporary end-to-end verification product",shortDescription:"Temporary product",currentPrice:79.99,oldPrice:99.99,discountPercent:20,rating:4.7,reviewCount:123,affiliateUrl:"https://example.com/deal",ctaLabel:"View Deal",badge:"Test",sku:"TEST-001",availability:"In stock",tags:["test"],status:"ACTIVE",featured:false,categoryId:category.id,brandId:brand.id,storeId:store.id,images:[]});created.push(["products",product.id]);
product=await request(`/admin/products/${product.id}`,"PATCH",{...product,title:"CRUD Test Product Updated",currentPrice:74.99,featured:true,images:[]});assert.equal(product.title,"CRUD Test Product Updated");assert.equal(product.featured,true);
await request(`/admin/products/${product.id}/toggle`,"POST",{active:false});await request(`/admin/products/${product.id}/toggle`,"POST",{active:true});
const deal=await request("/admin/deals","POST",{slug:"crud-test-deal",productId:product.id,discountPercent:25,startsAt:new Date(Date.now()-60000),endsAt:new Date(Date.now()+86400000),badge:"Hot Deal",featured:true,status:"ACTIVE"});created.push(["deals",deal.id]);
const banner=await request("/admin/banners","POST",{title:"CRUD Verification Offer",subtitle:"Temporary banner",background:"#071225",buttonLabel:"See offer",buttonUrl:"https://example.com",storeId:store.id,sortOrder:4,status:"ACTIVE"});created.push(["banners",banner.id]);
const post=await request("/admin/blog","POST",{title:"CRUD Verification Article",slug:"crud-verification-article",excerpt:"Temporary verification post",content:"This temporary article verifies persistence.",author:"Test Admin",tags:["test"],status:"ACTIVE",publishedAt:new Date(),readingTime:3});created.push(["blog",post.id]);
const section=await request("/admin/homepage-sections","POST",{type:"FEATURED_PRODUCTS",title:"CRUD Verification Deals",sortOrder:20,visible:true,productIds:[product.id],categoryIds:[],storeIds:[],config:{}});created.push(["homepage-sections",section.id]);await request(`/admin/homepage-sections/${section.id}/move`,"POST",{direction:"up"});
const blogSection=await request("/admin/homepage-sections","POST",{type:"BLOG",title:"CRUD Verification Blog",sortOrder:21,visible:true,productIds:[],categoryIds:[],storeIds:[],config:{}});created.push(["homepage-sections",blogSection.id]);
const nav=await request("/admin/navigation","POST",{label:"CRUD Test",url:"/crud-test",sortOrder:99,active:true});created.push(["navigation",nav.id]);
const footer=await request("/admin/footer","POST",{title:"CRUD Test Links",content:"Temporary",sortOrder:99,active:true,links:[{label:"Test",url:"/crud-test"}]});created.push(["footer",footer.id]);
const affiliate=await request("/admin/affiliate-links","POST",{label:"CRUD Test Affiliate",url:"https://example.com/affiliate",productId:product.id,clickCount:0,active:true});created.push(["affiliate-links",affiliate.id]);
const seo=await request("/admin/seo","POST",{entityType:"test",entityId:"crud-test",title:"CRUD Test SEO",description:"Temporary",canonicalUrl:"https://example.com/crud-test",noIndex:true,jsonLd:{"@type":"Thing"}});created.push(["seo",seo.id]);
const secondAdmin=await request("/admin/admins","POST",{name:"CRUD Test Editor",email:"crud-editor@example.com",password:"TemporaryPass123",role:"EDITOR",active:true});created.push(["admins",secondAdmin.id]);
const settings=await request("/admin/settings","PUT",{websiteName:"Bargain MOM Test",primaryColor:"#071225",accentColor:"#ff5a0a",supportEmail:"admin@example.com",headerCtaLabel:"Test Deals",headerCtaUrl:"/deals",socialMedia:{},analyticsIds:{}});assert.equal(settings.websiteName,"Bargain MOM Test");assert.equal((await request("/admin/settings")).websiteName,"Bargain MOM Test");
const homepage=await request("/homepage");assert(homepage.sections.some(x=>x.title==="CRUD Verification Deals"));assert(homepage.sections.some(x=>x.title==="CRUD Verification Offer"));assert(homepage.sections.some(x=>x.posts?.some(p=>p.slug==="crud-verification-article")));
assert((await request("/admin/products")).some(x=>x.id===product.id));
for(const [resource,id] of created.slice().reverse())await request(`/admin/${resource}/${id}`,"DELETE");
await request("/admin/settings","PUT",{websiteName:"Bargain MOM",primaryColor:"#071225",accentColor:"#ff5a0a",supportEmail:"",headerCtaLabel:"Today’s Deals",headerCtaUrl:"/deals",socialMedia:{},analyticsIds:{}});
console.log("Authenticated PostgreSQL CRUD suite passed and temporary records were removed.");
