import { Router } from "express";
import { Prisma, PrismaClient } from "@prisma/client";
import { z } from "zod";
import { requireAdmin } from "./auth.js";
import multer from "multer";
import { v2 as cloudinary } from "cloudinary";
import bcrypt from "bcryptjs";

const optionalUrl=z.union([z.string().url(),z.literal(""),z.null()]).optional().transform(v=>v||null);
const optionalString=z.union([z.string(),z.null()]).optional().transform(v=>v||null);
const status=z.enum(["DRAFT","ACTIVE","INACTIVE","ARCHIVED"]).optional();
const base={id:z.string().optional(),createdAt:z.unknown().optional(),updatedAt:z.unknown().optional()};
const schemas={
  products:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),description:optionalString,shortDescription:optionalString,currentPrice:z.coerce.number().nonnegative().nullable().optional(),oldPrice:z.coerce.number().nonnegative().nullable().optional(),discountPercent:z.coerce.number().int().min(0).max(100).nullable().optional(),rating:z.coerce.number().min(0).max(5).nullable().optional(),reviewCount:z.coerce.number().int().nonnegative().default(0),affiliateUrl:z.string().url(),ctaLabel:z.string().default("View deal"),badge:optionalString,sku:optionalString,availability:optionalString,tags:z.array(z.string()).default([]),status:status.default("DRAFT"),featured:z.coerce.boolean().default(false),seoTitle:optionalString,seoDescription:optionalString,categoryId:optionalString,brandId:optionalString,storeId:optionalString,images:z.array(z.object({url:z.string().url(),altText:z.string().optional(),sortOrder:z.number().int().optional()})).default([])}),
  categories:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),icon:optionalString,image:optionalUrl,description:optionalString,status:status.default("ACTIVE"),sortOrder:z.coerce.number().int().default(0),seoTitle:optionalString,seoDescription:optionalString,parentId:optionalString}),
  stores:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),logo:optionalUrl,description:optionalString,websiteUrl:optionalUrl,affiliateBaseUrl:optionalUrl,color:optionalString,active:z.coerce.boolean().default(true),seoTitle:optionalString,seoDescription:optionalString}),
  brands:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),logo:optionalUrl,description:optionalString,active:z.coerce.boolean().default(true),seoTitle:optionalString,seoDescription:optionalString}),
  deals:z.object({...base,slug:z.string().min(2).regex(/^[a-z0-9-]+$/),productId:z.string().min(1),discountPercent:z.coerce.number().int().min(0).max(100).nullable().optional(),startsAt:z.coerce.date(),endsAt:z.coerce.date(),status:status.default("DRAFT"),featured:z.coerce.boolean().default(false),badge:optionalString}).refine(v=>v.endsAt>v.startsAt,{message:"End date must be after start date",path:["endsAt"]}),
  banners:z.object({...base,title:z.string().min(2),subtitle:optionalString,image:optionalUrl,logo:optionalUrl,background:optionalString,buttonLabel:optionalString,buttonUrl:optionalUrl,startsAt:z.coerce.date().nullable().optional(),endsAt:z.coerce.date().nullable().optional(),status:status.default("DRAFT"),sortOrder:z.coerce.number().int().default(0),storeId:optionalString}).refine(v=>!v.startsAt||!v.endsAt||v.endsAt>v.startsAt,{message:"End date must be after start date",path:["endsAt"]}),
  "homepage-sections":z.object({...base,type:z.enum(["HERO","STORE_LOGOS","FEATURED_PRODUCTS","CATEGORY_GRID","STORE_PRODUCTS","PROMO_BANNER","BLOG","TRUST_FEATURES","CUSTOM"]),title:optionalString,subtitle:optionalString,sortOrder:z.coerce.number().int().default(0),visible:z.coerce.boolean().default(true),maxItems:z.coerce.number().int().positive().nullable().optional(),background:optionalString,ctaText:optionalString,ctaUrl:optionalString,config:z.record(z.string(),z.unknown()).nullable().optional(),productIds:z.array(z.string()).default([]),categoryIds:z.array(z.string()).default([]),storeIds:z.array(z.string()).default([])}),
  blog:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),excerpt:optionalString,content:z.string().min(1),coverImage:optionalUrl,author:optionalString,tags:z.array(z.string()).default([]),status:status.default("DRAFT"),publishedAt:z.coerce.date().nullable().optional(),readingTime:z.coerce.number().int().positive().nullable().optional(),seoTitle:optionalString,seoDescription:optionalString,categoryId:optionalString}),
  navigation:z.object({...base,label:z.string().min(1),url:z.string().min(1),sortOrder:z.coerce.number().int().default(0),active:z.coerce.boolean().default(true),parentId:optionalString}),
  footer:z.object({...base,title:z.string().min(1),content:optionalString,sortOrder:z.coerce.number().int().default(0),active:z.coerce.boolean().default(true),links:z.array(z.object({id:z.string().optional(),label:z.string().min(1),url:z.string().min(1)})).default([])}),
  "affiliate-links":z.object({...base,label:z.string().min(1),url:z.string().url(),clickCount:z.coerce.number().int().nonnegative().default(0),active:z.coerce.boolean().default(true),productId:optionalString}),
  seo:z.object({...base,entityType:z.string().min(1),entityId:optionalString,title:optionalString,description:optionalString,canonicalUrl:optionalUrl,openGraphImage:optionalUrl,noIndex:z.coerce.boolean().default(false),jsonLd:z.record(z.string(),z.unknown()).nullable().optional(),dealId:optionalString}),
};
type Resource=keyof typeof schemas;
const resources=new Set(Object.keys(schemas));
const include:Partial<Record<Resource,object>>={products:{images:true,category:true,brand:true,store:true},deals:{product:true},banners:{store:true},blog:{category:true},navigation:{parent:true},"homepage-sections":{products:{include:{product:true},orderBy:{sortOrder:"asc"}},categories:{include:{category:true},orderBy:{sortOrder:"asc"}},stores:{include:{store:true},orderBy:{sortOrder:"asc"}}}};
const modelName:Record<Resource,string>={products:"product",categories:"category",stores:"store",brands:"brand",deals:"deal",banners:"banner","homepage-sections":"homepageSection",blog:"blogPost",navigation:"navigationItem",footer:"footerSection","affiliate-links":"affiliateLink",seo:"seoMetadata"};

function success(res:any,data:any,statusCode=200){return res.status(statusCode).json({success:true,data})}
function sanitize(resource:Resource,raw:any,id?:string){const parsed=schemas[resource].parse(raw) as any;delete parsed.id;delete parsed.createdAt;delete parsed.updatedAt;if(resource==="categories"&&id&&parsed.parentId===id)throw new z.ZodError([{code:"custom",path:["parentId"],message:"A category cannot be its own parent",input:parsed.parentId} as any]);if(resource==="products"){const images=parsed.images;delete parsed.images;return {...parsed,images:id?{deleteMany:{},create:images}:{create:images}}}if(resource==="homepage-sections"){const {productIds,categoryIds,storeIds,...data}=parsed;const products=productIds.map((productId:string,sortOrder:number)=>({productId,sortOrder}));const categories=categoryIds.map((categoryId:string,sortOrder:number)=>({categoryId,sortOrder}));const stores=storeIds.map((storeId:string,sortOrder:number)=>({storeId,sortOrder}));return {...data,products:id?{deleteMany:{},create:products}:{create:products},categories:id?{deleteMany:{},create:categories}:{create:categories},stores:id?{deleteMany:{},create:stores}:{create:stores}}}return parsed}

export function adminRouter(prisma:PrismaClient){const router=Router();router.use(requireAdmin);
  const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(_req,file,cb)=>cb(null,["image/jpeg","image/png","image/webp","image/gif"].includes(file.mimetype))});
  router.post("/upload",upload.single("file"),async(req,res,next)=>{try{if(!process.env.CLOUDINARY_CLOUD_NAME||!process.env.CLOUDINARY_API_KEY||!process.env.CLOUDINARY_API_SECRET)return res.status(503).json({success:false,message:"Image storage is not configured"});if(!req.file)return res.status(400).json({success:false,message:"A valid image file is required"});cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});const result=await new Promise<any>((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:"affiliate-project",resource_type:"image"},(error,result)=>error?reject(error):resolve(result));stream.end(req.file!.buffer)});success(res,{url:result.secure_url,publicId:result.public_id},201)}catch(e){next(e)}});
  router.get("/overview",async(_req,res,next)=>{try{const [products,deals,stores,categories,posts,subscribers]=await Promise.all([prisma.product.count(),prisma.deal.count({where:{status:"ACTIVE"}}),prisma.store.count(),prisma.category.count(),prisma.blogPost.count(),prisma.newsletterSubscriber.count()]);success(res,{products,deals,stores,categories,posts,subscribers})}catch(e){next(e)}});
  router.get("/options",async(_req,res,next)=>{try{const [products,categories,stores,brands,blogCategories]=await Promise.all([prisma.product.findMany({select:{id:true,title:true}}),prisma.category.findMany({select:{id:true,name:true}}),prisma.store.findMany({select:{id:true,name:true}}),prisma.brand.findMany({select:{id:true,name:true}}),prisma.blogCategory.findMany({select:{id:true,name:true}})]);success(res,{products,categories,stores,brands,blogCategories})}catch(e){next(e)}});
  router.get("/admins",async(_req,res,next)=>{try{success(res,await prisma.admin.findMany({select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true},orderBy:{createdAt:"asc"}}))}catch(e){next(e)}});
  router.post("/admins",async(req,res,next)=>{try{const value=z.object({email:z.string().email(),name:z.string().min(2),password:z.string().min(10),role:z.enum(["OWNER","ADMIN","EDITOR"]),active:z.coerce.boolean().default(true)}).parse(req.body);success(res,await prisma.admin.create({data:{email:value.email,name:value.name,passwordHash:await bcrypt.hash(value.password,12),role:value.role,active:value.active},select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true}}),201)}catch(e){next(e)}});
  router.patch("/admins/:id",async(req,res,next)=>{try{const value=z.object({email:z.string().email(),name:z.string().min(2),password:z.string().min(10).optional(),role:z.enum(["OWNER","ADMIN","EDITOR"]),active:z.coerce.boolean()}).parse(req.body);const {password,...fields}=value;success(res,await prisma.admin.update({where:{id:req.params.id},data:{...fields,...(password?{passwordHash:await bcrypt.hash(password,12)}:{})},select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true}}))}catch(e){next(e)}});
  router.delete("/admins/:id",async(req,res,next)=>{try{if(res.locals.admin?.sub===req.params.id)return res.status(400).json({success:false,message:"You cannot delete your own account"});await prisma.admin.delete({where:{id:req.params.id}});success(res,{id:req.params.id})}catch(e){next(e)}});
  router.post("/admins/:id/toggle",async(req,res,next)=>{try{if(res.locals.admin?.sub===req.params.id&&!req.body.active)return res.status(400).json({success:false,message:"You cannot deactivate your own account"});success(res,await prisma.admin.update({where:{id:req.params.id},data:{active:Boolean(req.body.active)},select:{id:true,email:true,name:true,role:true,active:true}}))}catch(e){next(e)}});
  router.get("/settings",async(_req,res,next)=>{try{success(res,await prisma.siteSettings.findUnique({where:{id:"global"}}))}catch(e){next(e)}});
  router.put("/settings",async(req,res,next)=>{try{const schema=z.object({websiteName:z.string().min(1),logo:optionalUrl,favicon:optionalUrl,primaryColor:z.string(),accentColor:z.string(),supportEmail:z.union([z.string().email(),z.literal("")]).optional().transform(v=>v||null),socialMedia:z.record(z.string(),z.unknown()).nullable().optional(),defaultSeoTitle:optionalString,defaultSeoDescription:optionalString,affiliateDisclosure:optionalString,copyright:optionalString,analyticsIds:z.record(z.string(),z.unknown()).nullable().optional(),searchPlaceholder:optionalString,headerCtaLabel:optionalString,headerCtaUrl:optionalString,footerDescription:optionalString,newsletterTitle:optionalString,newsletterText:optionalString});const data:any=schema.parse(req.body);success(res,await prisma.siteSettings.upsert({where:{id:"global"},create:{id:"global",...data},update:data}))}catch(e){next(e)}});
  router.get("/:resource",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const model=(prisma as any)[modelName[resource]];const orderBy=["homepage-sections","navigation","footer","categories","banners"].includes(resource)?{sortOrder:"asc"}:["products","deals","blog"].includes(resource)?{updatedAt:"desc"}:resource==="affiliate-links"?{createdAt:"desc"}:{id:"asc"};success(res,await model.findMany({include:include[resource],orderBy}))}catch(e){next(e)}});
  router.post("/:resource",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const data=sanitize(resource,req.body);success(res,await (prisma as any)[modelName[resource]].create({data,include:include[resource]}),201)}catch(e){next(e)}});
  router.patch("/:resource/:id",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const data=sanitize(resource,req.body,req.params.id);success(res,await (prisma as any)[modelName[resource]].update({where:{id:req.params.id},data,include:include[resource]}))}catch(e){next(e)}});
  router.delete("/:resource/:id",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});await (prisma as any)[modelName[resource]].delete({where:{id:req.params.id}});success(res,{id:req.params.id})}catch(e){next(e)}});
  router.post("/:resource/:id/toggle",async(req,res,next)=>{try{const resource=req.params.resource as Resource;const field=resource==="homepage-sections"?"visible":resource==="products"||resource==="categories"||resource==="deals"||resource==="banners"||resource==="blog"?"status":"active";const value=field==="status"?(req.body.active?"ACTIVE":"INACTIVE"):Boolean(req.body.active);success(res,await (prisma as any)[modelName[resource]].update({where:{id:req.params.id},data:{[field]:value}}))}catch(e){next(e)}});
  router.post("/:resource/:id/move",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!["homepage-sections","navigation","footer"].includes(resource))return res.status(400).json({success:false,message:"Resource cannot be reordered"});const direction=z.enum(["up","down"]).parse(req.body.direction);const model=(prisma as any)[modelName[resource]];const current=await model.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,message:"Record not found"});const adjacent=await model.findFirst({where:{sortOrder:direction==="up"?{lt:current.sortOrder}:{gt:current.sortOrder}},orderBy:{sortOrder:direction==="up"?"desc":"asc"}});if(adjacent)await prisma.$transaction([model.update({where:{id:current.id},data:{sortOrder:adjacent.sortOrder}}),model.update({where:{id:adjacent.id},data:{sortOrder:current.sortOrder}})]);success(res,{moved:Boolean(adjacent)})}catch(e){next(e)}});
  return router;
}

export function apiError(error:any,_req:any,res:any,_next:any){if(error instanceof z.ZodError)return res.status(400).json({success:false,message:"Validation failed",errors:error.flatten()});if(error instanceof Prisma.PrismaClientKnownRequestError){if(error.code==="P2002")return res.status(409).json({success:false,message:"A record with that unique value already exists"});if(error.code==="P2025")return res.status(404).json({success:false,message:"Record not found"});if(error.code==="P2003")return res.status(409).json({success:false,message:"This record is still used by related content"})}console.error(error);return res.status(500).json({success:false,message:"Unexpected server error"})}
