import { Router } from "express";
import { Prisma, PrismaClient } from "@prisma/client";
import { z } from "zod";
import { requireAdmin } from "./auth.js";
import multer from "multer";
import { v2 as cloudinary } from "cloudinary";
import bcrypt from "bcryptjs";

const optionalUrl=z.union([z.string().url(),z.literal(""),z.null()]).optional().transform(v=>v||null);
const optionalString=z.union([z.string(),z.null()]).optional().transform(v=>v||null);
const optionalDate=z.union([z.coerce.date(),z.literal(""),z.null()]).optional().transform(v=>v||null);
const status=z.enum(["DRAFT","ACTIVE","INACTIVE","ARCHIVED"]).optional();
const base={id:z.string().optional(),createdAt:z.unknown().optional(),updatedAt:z.unknown().optional()};
const faqItems=z.array(z.object({question:z.string().min(3),answer:z.string().min(3)})).default([]);
const seoFields={seoTitle:optionalString,seoDescription:optionalString,canonicalUrl:optionalUrl,ogTitle:optionalString,ogDescription:optionalString,ogImage:optionalUrl,robotsIndex:z.coerce.boolean().default(true),robotsFollow:z.coerce.boolean().default(true),schemaEnabled:z.coerce.boolean().default(true)};

const schemas={
  products:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),description:optionalString,shortDescription:optionalString,editorialSummary:optionalString,idealFor:optionalString,notIdealFor:optionalString,importantSpecs:z.record(z.string(),z.string()).nullable().optional(),comparisonNotes:optionalString,dealAnalysis:optionalString,alternativesNotes:optionalString,whatWeLike:optionalString,whatCouldBeBetter:optionalString,bestUseCases:z.array(z.string()).default([]),faqItems,currentPrice:z.coerce.number().nonnegative().nullable().optional(),oldPrice:z.coerce.number().nonnegative().nullable().optional(),discountPercent:z.coerce.number().int().min(0).max(100).nullable().optional(),rating:z.coerce.number().min(0).max(5).nullable().optional(),reviewCount:z.coerce.number().int().nonnegative().default(0),affiliateUrl:optionalUrl,ctaLabel:z.string().default("View deal"),badge:optionalString,sku:optionalString,availability:optionalString,keyFeatures:z.array(z.string()).default([]),pros:z.array(z.string()).default([]),cons:z.array(z.string()).default([]),whyRecommend:optionalString,bestFor:optionalString,buyingAdvice:optionalString,lastVerifiedAt:optionalDate,priceUpdatedAt:optionalDate,contentUpdatedAt:optionalDate,tags:z.array(z.string()).default([]),status:status.default("DRAFT"),featured:z.coerce.boolean().default(false),...seoFields,categoryId:optionalString,brandId:optionalString,storeId:optionalString,images:z.array(z.object({url:z.string().url(),altText:z.string().optional(),sortOrder:z.number().int().optional()})).default([])}),
  categories:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),h1:optionalString,icon:optionalString,image:optionalUrl,description:optionalString,editorialContent:optionalString,buyingTips:z.array(z.string()).default([]),faqItems,status:status.default("ACTIVE"),sortOrder:z.coerce.number().int().default(0),...seoFields,parentId:optionalString,featuredProductIds:z.array(z.string()).default([])}),
  stores:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),logo:optionalUrl,description:optionalString,editorialNotes:optionalString,shoppingTips:z.array(z.string()).default([]),faqItems,websiteUrl:optionalUrl,affiliateBaseUrl:optionalUrl,color:optionalString,active:z.coerce.boolean().default(true),...seoFields}),
  brands:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),logo:optionalUrl,description:optionalString,active:z.coerce.boolean().default(true),...seoFields}),
  deals:z.object({...base,slug:z.string().min(2).regex(/^[a-z0-9-]+$/),productId:z.string().min(1),discountPercent:z.coerce.number().int().min(0).max(100).nullable().optional(),startsAt:z.coerce.date(),endsAt:z.coerce.date(),status:status.default("DRAFT"),featured:z.coerce.boolean().default(false),badge:optionalString,...seoFields,robotsIndex:z.coerce.boolean().default(false),schemaEnabled:z.coerce.boolean().default(false)}).refine(v=>v.endsAt>v.startsAt,{message:"End date must be after start date",path:["endsAt"]}),
  banners:z.object({...base,title:z.string().min(2),subtitle:optionalString,image:optionalUrl,logo:optionalUrl,background:optionalString,buttonLabel:optionalString,buttonUrl:optionalUrl,startsAt:optionalDate,endsAt:optionalDate,status:status.default("DRAFT"),sortOrder:z.coerce.number().int().default(0),storeId:optionalString}).refine(v=>!v.startsAt||!v.endsAt||v.endsAt>v.startsAt,{message:"End date must be after start date",path:["endsAt"]}),
  "homepage-sections":z.object({...base,type:z.enum(["HERO","STORE_LOGOS","FEATURED_PRODUCTS","CATEGORY_GRID","STORE_PRODUCTS","PROMO_BANNER","BLOG","TRUST_FEATURES","CUSTOM"]),title:optionalString,subtitle:optionalString,sortOrder:z.coerce.number().int().default(0),visible:z.coerce.boolean().default(true),maxItems:z.coerce.number().int().positive().nullable().optional(),background:optionalString,ctaText:optionalString,ctaUrl:optionalString,config:z.record(z.string(),z.unknown()).nullable().optional(),productIds:z.array(z.string()).default([]),categoryIds:z.array(z.string()).default([]),storeIds:z.array(z.string()).default([])}).refine(value=>value.type!=="HERO"||Boolean(value.title?.trim()),{message:"A hero section needs an H1 title",path:["title"]}),
  blog:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),excerpt:optionalString,content:z.string().min(1),coverImage:optionalUrl,author:optionalString,authorId:optionalString,tags:z.array(z.string()).default([]),faqItems,status:status.default("DRAFT"),publishedAt:optionalDate,contentUpdatedAt:optionalDate,readingTime:z.coerce.number().int().positive().nullable().optional(),productIds:z.array(z.string()).default([]),guideIds:z.array(z.string()).default([]),commerceCategoryIds:z.array(z.string()).default([]),...seoFields,categoryId:optionalString}),
  authors:z.object({...base,name:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),bio:optionalString,profileImage:optionalUrl,expertise:z.array(z.string()).default([]),profileUrls:z.array(z.string().url()).default([]),active:z.coerce.boolean().default(true)}),
  guides:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),intro:z.string().min(30),body:optionalString,editorialSections:z.array(z.object({heading:z.string().min(2),body:z.string().min(10)})).default([]),heroImage:optionalUrl,heroImageAlt:optionalString,faqItems,status:status.default("DRAFT"),publishedAt:optionalDate,categoryId:optionalString,authorId:optionalString,productIds:z.array(z.string()).default([]),...seoFields}),
  comparisons:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),introduction:z.string().min(30),comparisonTable:z.array(z.object({label:z.string().min(1),values:z.array(z.string())})).default([]),strengths:z.record(z.string(),z.array(z.string())).nullable().optional(),weaknesses:z.record(z.string(),z.array(z.string())).nullable().optional(),pricingNotes:optionalString,bestFor:optionalString,verdict:optionalString,faqItems,heroImage:optionalUrl,heroImageAlt:optionalString,status:status.default("DRAFT"),publishedAt:optionalDate,authorId:optionalString,productIds:z.array(z.string()).default([]),storeIds:z.array(z.string()).default([]),...seoFields}),
  pages:z.object({...base,title:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),intro:optionalString,content:z.string().min(30),status:status.default("DRAFT"),publishedAt:optionalDate,...seoFields}),
  navigation:z.object({...base,label:z.string().min(1),url:z.string().min(1),sortOrder:z.coerce.number().int().default(0),active:z.coerce.boolean().default(true),parentId:optionalString}),
  footer:z.object({...base,title:z.string().min(1),content:optionalString,sortOrder:z.coerce.number().int().default(0),active:z.coerce.boolean().default(true),links:z.array(z.object({id:z.string().optional(),label:z.string().min(1),url:z.string().min(1)})).default([])}),
  "affiliate-links":z.object({...base,label:z.string().min(1),url:z.string().url(),clickCount:z.coerce.number().int().nonnegative().default(0),active:z.coerce.boolean().default(true),productId:optionalString}),
};
type Resource=keyof typeof schemas;
const resources=new Set(Object.keys(schemas));
const include:Partial<Record<Resource,object>>={products:{images:true,category:true,brand:true,store:true},categories:{featuredProducts:{include:{product:true},orderBy:{sortOrder:"asc"}}},deals:{product:true},banners:{store:true},blog:{category:true,authorProfile:true,productPlacements:{include:{product:true},orderBy:{sortOrder:"asc"}},guidePlacements:{include:{guide:true},orderBy:{sortOrder:"asc"}},commerceCategoryPlacements:{include:{category:true},orderBy:{sortOrder:"asc"}}},guides:{category:true,author:true,products:{include:{product:true},orderBy:{sortOrder:"asc"}}},comparisons:{author:true,products:{include:{product:true},orderBy:{sortOrder:"asc"}},stores:{include:{store:true},orderBy:{sortOrder:"asc"}}},navigation:{parent:true},"homepage-sections":{products:{include:{product:true},orderBy:{sortOrder:"asc"}},categories:{include:{category:true},orderBy:{sortOrder:"asc"}},stores:{include:{store:true},orderBy:{sortOrder:"asc"}}}};
const modelName:Record<Resource,string>={products:"product",categories:"category",stores:"store",brands:"brand",deals:"deal",banners:"banner","homepage-sections":"homepageSection",blog:"blogPost",authors:"author",guides:"buyingGuide",comparisons:"comparison",pages:"editorialPage",navigation:"navigationItem",footer:"footerSection","affiliate-links":"affiliateLink"};

function success(res:any,data:any,statusCode=200){return res.status(statusCode).json({success:true,data})}
function sanitize(resource:Resource,raw:any,id?:string){
  const parsed=schemas[resource].parse(raw) as any;delete parsed.id;delete parsed.createdAt;delete parsed.updatedAt;
  if(["blog","guides","comparisons"].includes(resource)&&parsed.status==="ACTIVE"){
    if(!parsed.publishedAt)throw new z.ZodError([{code:"custom",path:["publishedAt"],message:"Published content needs a publication date",input:parsed.publishedAt} as any]);
    if(!parsed.authorId&&!(resource==="blog"&&parsed.author?.trim()))throw new z.ZodError([{code:"custom",path:["authorId"],message:"Published editorial content needs a visible author",input:parsed.authorId} as any]);
  }
  if(resource==="categories"&&id&&parsed.parentId===id)throw new z.ZodError([{code:"custom",path:["parentId"],message:"A category cannot be its own parent",input:parsed.parentId} as any]);
  if(resource==="products"){const images=parsed.images;delete parsed.images;return {...parsed,images:id?{deleteMany:{},create:images}:{create:images}}}
  if(resource==="categories"){const ids=parsed.featuredProductIds;delete parsed.featuredProductIds;const rows=ids.map((productId:string,sortOrder:number)=>({productId,sortOrder}));return {...parsed,featuredProducts:id?{deleteMany:{},create:rows}:{create:rows}}}
  if(resource==="blog"){const {productIds,guideIds,commerceCategoryIds,...data}=parsed;const products=productIds.map((productId:string,sortOrder:number)=>({productId,sortOrder}));const guides=guideIds.map((guideId:string,sortOrder:number)=>({guideId,sortOrder}));const categories=commerceCategoryIds.map((categoryId:string,sortOrder:number)=>({categoryId,sortOrder}));return {...data,productPlacements:id?{deleteMany:{},create:products}:{create:products},guidePlacements:id?{deleteMany:{},create:guides}:{create:guides},commerceCategoryPlacements:id?{deleteMany:{},create:categories}:{create:categories}}}
  if(resource==="guides"){const ids=parsed.productIds;delete parsed.productIds;const rows=ids.map((productId:string,sortOrder:number)=>({productId,sortOrder}));return {...parsed,products:id?{deleteMany:{},create:rows}:{create:rows}}}
  if(resource==="comparisons"){const productIds=parsed.productIds,storeIds=parsed.storeIds;delete parsed.productIds;delete parsed.storeIds;const products=productIds.map((productId:string,sortOrder:number)=>({productId,sortOrder}));const stores=storeIds.map((storeId:string,sortOrder:number)=>({storeId,sortOrder}));return {...parsed,products:id?{deleteMany:{},create:products}:{create:products},stores:id?{deleteMany:{},create:stores}:{create:stores}}}
  if(resource==="homepage-sections"){const {productIds,categoryIds,storeIds,...data}=parsed;const products=productIds.map((productId:string,sortOrder:number)=>({productId,sortOrder}));const categories=categoryIds.map((categoryId:string,sortOrder:number)=>({categoryId,sortOrder}));const stores=storeIds.map((storeId:string,sortOrder:number)=>({storeId,sortOrder}));return {...data,products:id?{deleteMany:{},create:products}:{create:products},categories:id?{deleteMany:{},create:categories}:{create:categories},stores:id?{deleteMany:{},create:stores}:{create:stores}}}
  return parsed;
}

async function seoAudit(prisma:PrismaClient){
  const [products,categories,stores,brands,posts,guides,comparisons,pages]=await Promise.all([
    prisma.product.findMany({where:{status:"ACTIVE",robotsIndex:true},include:{images:true}}),
    prisma.category.findMany({where:{status:"ACTIVE",robotsIndex:true}}),prisma.store.findMany({where:{active:true,robotsIndex:true}}),prisma.brand.findMany({where:{active:true,robotsIndex:true}}),
    prisma.blogPost.findMany({where:{status:"ACTIVE",robotsIndex:true}}),prisma.buyingGuide.findMany({where:{status:"ACTIVE",robotsIndex:true}}),prisma.comparison.findMany({where:{status:"ACTIVE",robotsIndex:true}}),prisma.editorialPage.findMany({where:{status:"ACTIVE",robotsIndex:true}}),
  ]);
  const items:any[]=[];const add=(type:string,row:any,path:string,warnings:string[])=>items.push({id:row.id,type,title:row.title||row.name,path,warnings});const common=(row:any,content?:string|null)=>[...(!row.seoTitle?["Missing SEO title override (automatic fallback is active)"]:[]),...(!row.seoDescription?["Missing meta description override (automatic fallback is active)"]:[]),...(!row.canonicalUrl?["Missing canonical override (self-canonical fallback is active)"]:[]),...(String(content||"").trim().length<120?["Thin editorial content"]:[])];
  for(const row of products){const warnings=common(row,row.editorialSummary||row.description);if(!row.images.length)warnings.push("Missing product image");if(row.images.some(x=>!x.altText))warnings.push("Missing image alt text");if(!row.affiliateUrl)warnings.push("Affiliate URL missing");if(!row.categoryId&&!row.brandId&&!row.storeId)warnings.push("Missing contextual internal links");if(!row.lastVerifiedAt)warnings.push("Price verification date not recorded");else if(Date.now()-row.lastVerifiedAt.getTime()>30*86400000)warnings.push("Price verification is older than 30 days");add("Product",row,`/product/${row.slug}`,warnings)}
  for(const row of categories)add("Category",row,`/category/${row.slug}`,common(row,row.editorialContent||row.description));for(const row of stores)add("Store",row,`/store/${row.slug}`,common(row,row.editorialNotes||row.description));for(const row of brands)add("Brand",row,`/brand/${row.slug}`,common(row,row.description));for(const row of posts){const warnings=common(row,row.content);if(!row.authorId&&!row.author)warnings.push("Missing visible author");if(!row.publishedAt)warnings.push("Missing publication date");add("Blog",row,`/blog/${row.slug}`,warnings)}for(const row of guides){const warnings=common(row,`${row.intro} ${row.body||""}`);if(!row.authorId)warnings.push("Missing visible author");if(!row.publishedAt)warnings.push("Missing publication date");add("Guide",row,`/guides/${row.slug}`,warnings)}for(const row of comparisons){const warnings=common(row,`${row.introduction} ${row.verdict||""}`);if(!row.authorId)warnings.push("Missing visible author");if(!row.publishedAt)warnings.push("Missing publication date");add("Comparison",row,`/compare/${row.slug}`,warnings)}for(const row of pages)add("Page",row,`/${row.slug}`,common(row,row.content));
  return {summary:{checked:items.length,withWarnings:items.filter(x=>x.warnings.length).length,warnings:items.reduce((n,x)=>n+x.warnings.length,0)},items};
}

export function adminRouter(prisma:PrismaClient){const router=Router();router.use(requireAdmin);
  const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(_req,file,cb)=>cb(null,["image/jpeg","image/png","image/webp","image/gif"].includes(file.mimetype))});
  router.post("/upload",upload.single("file"),async(req,res,next)=>{try{if(!process.env.CLOUDINARY_CLOUD_NAME||!process.env.CLOUDINARY_API_KEY||!process.env.CLOUDINARY_API_SECRET)return res.status(503).json({success:false,message:"Image storage is not configured"});if(!req.file)return res.status(400).json({success:false,message:"A valid image file is required"});cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});const result=await new Promise<any>((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:"affiliate-project",resource_type:"image"},(error,result)=>error?reject(error):resolve(result));stream.end(req.file!.buffer)});success(res,{url:result.secure_url,publicId:result.public_id},201)}catch(e){next(e)}});
  router.get("/overview",async(_req,res,next)=>{try{const [products,deals,stores,categories,posts,subscribers,guides,comparisons]=await Promise.all([prisma.product.count(),prisma.deal.count({where:{status:"ACTIVE"}}),prisma.store.count(),prisma.category.count(),prisma.blogPost.count(),prisma.newsletterSubscriber.count(),prisma.buyingGuide.count(),prisma.comparison.count()]);success(res,{products,deals,stores,categories,posts,subscribers,guides,comparisons})}catch(e){next(e)}});
  router.get("/options",async(_req,res,next)=>{try{const [products,categories,stores,brands,blogCategories,authors,guides]=await Promise.all([prisma.product.findMany({select:{id:true,title:true}}),prisma.category.findMany({select:{id:true,name:true}}),prisma.store.findMany({select:{id:true,name:true}}),prisma.brand.findMany({select:{id:true,name:true}}),prisma.blogCategory.findMany({select:{id:true,name:true}}),prisma.author.findMany({select:{id:true,name:true}}),prisma.buyingGuide.findMany({select:{id:true,title:true}})]);success(res,{products,categories,stores,brands,blogCategories,authors,guides})}catch(e){next(e)}});
  router.get("/seo-audit",async(_req,res,next)=>{try{success(res,await seoAudit(prisma))}catch(e){next(e)}});
  router.get("/admins",async(_req,res,next)=>{try{success(res,await prisma.admin.findMany({select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true},orderBy:{createdAt:"asc"}}))}catch(e){next(e)}});
  router.post("/admins",async(req,res,next)=>{try{const value=z.object({email:z.string().email(),name:z.string().min(2),password:z.string().min(10),role:z.enum(["OWNER","ADMIN","EDITOR"]),active:z.coerce.boolean().default(true)}).parse(req.body);success(res,await prisma.admin.create({data:{email:value.email,name:value.name,passwordHash:await bcrypt.hash(value.password,12),role:value.role,active:value.active},select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true}}),201)}catch(e){next(e)}});
  router.patch("/admins/:id",async(req,res,next)=>{try{const value=z.object({email:z.string().email(),name:z.string().min(2),password:z.string().min(10).optional(),role:z.enum(["OWNER","ADMIN","EDITOR"]),active:z.coerce.boolean()}).parse(req.body);const {password,...fields}=value;success(res,await prisma.admin.update({where:{id:req.params.id},data:{...fields,...(password?{passwordHash:await bcrypt.hash(password,12)}:{})},select:{id:true,email:true,name:true,role:true,active:true,createdAt:true,updatedAt:true}}))}catch(e){next(e)}});
  router.delete("/admins/:id",async(req,res,next)=>{try{if(res.locals.admin?.sub===req.params.id)return res.status(400).json({success:false,message:"You cannot delete your own account"});await prisma.admin.delete({where:{id:req.params.id}});success(res,{id:req.params.id})}catch(e){next(e)}});
  router.post("/admins/:id/toggle",async(req,res,next)=>{try{if(res.locals.admin?.sub===req.params.id&&!req.body.active)return res.status(400).json({success:false,message:"You cannot deactivate your own account"});success(res,await prisma.admin.update({where:{id:req.params.id},data:{active:Boolean(req.body.active)},select:{id:true,email:true,name:true,role:true,active:true}}))}catch(e){next(e)}});
  router.get("/settings",async(_req,res,next)=>{try{success(res,await prisma.siteSettings.findUnique({where:{id:"global"}}))}catch(e){next(e)}});
  router.put("/settings",async(req,res,next)=>{try{const schema=z.object({websiteName:z.string().min(1),logo:optionalUrl,favicon:optionalUrl,primaryColor:z.string(),accentColor:z.string(),supportEmail:z.union([z.string().email(),z.literal("")]).optional().transform(v=>v||null),socialMedia:z.record(z.string(),z.unknown()).nullable().optional(),defaultSeoTitle:optionalString,defaultSeoDescription:optionalString,siteUrl:optionalUrl,homepageSeoTitle:optionalString,homepageSeoDescription:optionalString,homepageCanonicalUrl:optionalUrl,homepageOgTitle:optionalString,homepageOgDescription:optionalString,homepageOgImage:optionalUrl,homepageRobotsIndex:z.coerce.boolean().optional(),homepageRobotsFollow:z.coerce.boolean().optional(),homepageSchemaEnabled:z.coerce.boolean().optional(),googleSiteVerification:optionalString,bingSiteVerification:optionalString,affiliateDisclosure:optionalString,copyright:optionalString,analyticsIds:z.record(z.string(),z.unknown()).nullable().optional(),searchPlaceholder:optionalString,headerCtaLabel:optionalString,headerCtaUrl:optionalString,footerDescription:optionalString,newsletterTitle:optionalString,newsletterText:optionalString});const data:any=schema.parse(req.body);success(res,await prisma.siteSettings.upsert({where:{id:"global"},create:{id:"global",...data},update:data}))}catch(e){next(e)}});
  router.get("/:resource",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const model=(prisma as any)[modelName[resource]];const orderBy=["homepage-sections","navigation","footer","categories","banners"].includes(resource)?{sortOrder:"asc"}:["products","deals","blog","guides","comparisons","pages"].includes(resource)?{updatedAt:"desc"}:resource==="affiliate-links"?{createdAt:"desc"}:{id:"asc"};success(res,await model.findMany({include:include[resource],orderBy}))}catch(e){next(e)}});
  router.post("/:resource",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const data=sanitize(resource,req.body);success(res,await (prisma as any)[modelName[resource]].create({data,include:include[resource]}),201)}catch(e){next(e)}});
  router.patch("/:resource/:id",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const data=sanitize(resource,req.body,req.params.id);success(res,await (prisma as any)[modelName[resource]].update({where:{id:req.params.id},data,include:include[resource]}))}catch(e){next(e)}});
  router.delete("/:resource/:id",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});await (prisma as any)[modelName[resource]].delete({where:{id:req.params.id}});success(res,{id:req.params.id})}catch(e){next(e)}});
  router.post("/:resource/:id/toggle",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!resources.has(resource))return res.status(404).json({success:false,message:"Unknown resource"});const field=resource==="homepage-sections"?"visible":["products","categories","deals","banners","blog","guides","comparisons","pages"].includes(resource)?"status":"active";const value=field==="status"?(req.body.active?"ACTIVE":"INACTIVE"):Boolean(req.body.active);success(res,await (prisma as any)[modelName[resource]].update({where:{id:req.params.id},data:{[field]:value}}))}catch(e){next(e)}});
  router.post("/:resource/:id/move",async(req,res,next)=>{try{const resource=req.params.resource as Resource;if(!["homepage-sections","navigation","footer"].includes(resource))return res.status(400).json({success:false,message:"Resource cannot be reordered"});const direction=z.enum(["up","down"]).parse(req.body.direction);const model=(prisma as any)[modelName[resource]];const current=await model.findUnique({where:{id:req.params.id}});if(!current)return res.status(404).json({success:false,message:"Record not found"});const adjacent=await model.findFirst({where:{sortOrder:direction==="up"?{lt:current.sortOrder}:{gt:current.sortOrder}},orderBy:{sortOrder:direction==="up"?"desc":"asc"}});if(adjacent)await prisma.$transaction([model.update({where:{id:current.id},data:{sortOrder:adjacent.sortOrder}}),model.update({where:{id:adjacent.id},data:{sortOrder:current.sortOrder}})]);success(res,{moved:Boolean(adjacent)})}catch(e){next(e)}});
  return router;
}

export function apiError(error:any,_req:any,res:any,_next:any){if(error instanceof z.ZodError)return res.status(400).json({success:false,message:"Validation failed",errors:error.flatten()});if(error instanceof Prisma.PrismaClientKnownRequestError){if(error.code==="P2002")return res.status(409).json({success:false,message:"A record with that unique value already exists"});if(error.code==="P2025")return res.status(404).json({success:false,message:"Record not found"});if(error.code==="P2003")return res.status(409).json({success:false,message:"This record is still used by related content"})}console.error(error);return res.status(500).json({success:false,message:"Unexpected server error"})}
