import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import cookieParser from "cookie-parser";
import { PrismaClient } from "@prisma/client";
import { z } from "zod";
import { authRouter } from "./auth.js";
import { adminRouter, apiError } from "./admin.js";

export const prisma=new PrismaClient();
const app=express();
app.use(helmet());
app.use(cors({origin:process.env.FRONTEND_URL,credentials:true}));
app.use(express.json({limit:"1mb"}));
app.use(cookieParser());
app.use("/api/auth",rateLimit({windowMs:60_000,limit:20}),authRouter);
app.use("/api/admin",adminRouter(prisma));

const active={status:"ACTIVE" as const};
const publishedNow=()=>({status:"ACTIVE" as const,publishedAt:{not:null,lte:new Date()}});
const liveDeal=()=>({status:"ACTIVE" as const,startsAt:{lte:new Date()},endsAt:{gt:new Date()}});
const pageOf=(raw:unknown)=>Math.max(1,Math.min(10_000,Number.parseInt(String(raw||"1"),10)||1));
const pageSizeOf=(raw:unknown)=>Math.max(1,Math.min(48,Number.parseInt(String(raw||"12"),10)||12));
const pagination=(page:number,pageSize:number,total:number)=>({page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize)),hasPrevious:page>1,hasNext:page*pageSize<total});
const cardInclude=()=>({images:{orderBy:{sortOrder:"asc" as const},take:1},brand:true,category:true,store:true,deals:{where:liveDeal(),orderBy:{discountPercent:"desc" as const},take:1}});
const homepageCardInclude=()=>({...cardInclude(),_count:{select:{deals:{where:{status:"ACTIVE" as const,endsAt:{lte:new Date()}}}}}});
function card(product:any){const {_count,...record}=product;const deal=product.deals?.[0];const demo=Array.isArray(product.tags)&&product.tags.includes("demo-seed");return {...record,image:product.images?.[0]?.url,activeDeal:deal||null,discountPercent:deal?.discountPercent??null,badge:deal?.badge??(demo?"Demo data":null),oldPrice:deal?product.oldPrice:null}}
function homepageProducts(sectionType:string,placements:any[],maxItems?:number|null){const activeDealModule=sectionType==="FEATURED_PRODUCTS"||sectionType==="STORE_PRODUCTS";return placements.filter(({product})=>!activeDealModule||!product._count?.deals||Boolean(product.deals?.[0])).slice(0,maxItems||undefined).map(({product})=>card(product))}

app.get("/api/settings",async(_req,res)=>res.json(await prisma.siteSettings.findUnique({where:{id:"global"}})||{}));
app.get("/api/navigation",async(_req,res)=>res.json(await prisma.navigationItem.findMany({where:{active:true,parentId:null},include:{children:{where:{active:true},orderBy:{sortOrder:"asc"}}},orderBy:{sortOrder:"asc"}})));
app.get("/api/footer",async(_req,res)=>res.json({columns:await prisma.footerSection.findMany({where:{active:true},orderBy:{sortOrder:"asc"}})}));

app.get("/api/products",async(req,res)=>{const q=String(req.query.q||"").trim(),page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize);const where:any={...active,...(q?{OR:[{title:{contains:q,mode:"insensitive"}},{description:{contains:q,mode:"insensitive"}},{editorialSummary:{contains:q,mode:"insensitive"}},{brand:{name:{contains:q,mode:"insensitive"}}},{category:{name:{contains:q,mode:"insensitive"}}},{store:{name:{contains:q,mode:"insensitive"}}}]}:{})};const [rows,total]=await Promise.all([prisma.product.findMany({where,include:cardInclude(),orderBy:[{featured:"desc"},{updatedAt:"desc"}],skip:(page-1)*pageSize,take:pageSize}),prisma.product.count({where})]);res.json({items:rows.map(card),pagination:pagination(page,pageSize,total),query:q})});

app.get("/api/products/:slug",async(req,res)=>{const product:any=await prisma.product.findFirst({where:{slug:req.params.slug,status:"ACTIVE"},include:{images:{orderBy:{sortOrder:"asc"}},brand:true,category:{include:{parent:true}},store:true,deals:{where:liveDeal(),orderBy:{discountPercent:"desc"},take:1},buyingGuidePlacements:{where:{guide:publishedNow()},include:{guide:{include:{category:true}}},orderBy:{sortOrder:"asc"}}}});if(!product)return res.status(404).json({message:"Product not found"});const relatedWhere:any={status:"ACTIVE",id:{not:product.id},OR:[...(product.categoryId?[{categoryId:product.categoryId}]:[]),...(product.brandId?[{brandId:product.brandId}]:[]),...(product.storeId?[{storeId:product.storeId}]:[])]};const [relatedProducts,moreFromStore,settings]=await Promise.all([relatedWhere.OR.length?prisma.product.findMany({where:relatedWhere,include:cardInclude(),take:6,orderBy:[{featured:"desc"},{updatedAt:"desc"}]}):[],product.storeId?prisma.product.findMany({where:{status:"ACTIVE",id:{not:product.id},storeId:product.storeId},include:cardInclude(),take:6,orderBy:[{featured:"desc"},{updatedAt:"desc"}]}):[],prisma.siteSettings.findUnique({where:{id:"global"},select:{affiliateDisclosure:true}})]);const currentDeal=product.deals?.[0]||null;const demo=Array.isArray(product.tags)&&product.tags.includes("demo-seed");res.json({...product,activeDeal:currentDeal,discountPercent:currentDeal?.discountPercent??null,badge:currentDeal?.badge??(demo?"Demo data":null),oldPrice:currentDeal?product.oldPrice:null,relatedProducts:relatedProducts.map(card),moreFromStore:moreFromStore.map(card),relatedGuides:product.buyingGuidePlacements.map((x:any)=>x.guide),affiliateDisclosure:settings?.affiliateDisclosure||null})});

app.get("/api/categories",async(_req,res)=>res.json(await prisma.category.findMany({where:active,orderBy:{sortOrder:"asc"}})));
app.get("/api/categories/:slug",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize);const category:any=await prisma.category.findFirst({where:{slug:req.params.slug,status:"ACTIVE"},include:{parent:true,children:{where:{status:"ACTIVE"},orderBy:{sortOrder:"asc"}},featuredProducts:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}},guides:{where:publishedNow(),include:{author:true},orderBy:{updatedAt:"desc"},take:6}}});if(!category)return res.status(404).json({message:"Category not found"});const where={status:"ACTIVE" as const,categoryId:category.id};const [products,total,brandRows]=await Promise.all([prisma.product.findMany({where,include:cardInclude(),orderBy:[{featured:"desc"},{updatedAt:"desc"}],skip:(page-1)*pageSize,take:pageSize}),prisma.product.count({where}),prisma.product.findMany({where:{...where,brandId:{not:null}},select:{brand:true},distinct:["brandId"],take:8})]);res.json({...category,featuredProducts:category.featuredProducts.map((x:any)=>card(x.product)),products:products.map(card),topBrands:brandRows.map(x=>x.brand).filter(Boolean),pagination:pagination(page,pageSize,total)})});

app.get("/api/stores",async(_req,res)=>res.json(await prisma.store.findMany({where:{active:true},orderBy:{name:"asc"}})));
app.get("/api/stores/:slug",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize);const store:any=await prisma.store.findFirst({where:{slug:req.params.slug,active:true}});if(!store)return res.status(404).json({message:"Store not found"});const where={status:"ACTIVE" as const,storeId:store.id};const [products,total,categoryRows,guides]=await Promise.all([prisma.product.findMany({where,include:cardInclude(),orderBy:[{featured:"desc"},{updatedAt:"desc"}],skip:(page-1)*pageSize,take:pageSize}),prisma.product.count({where}),prisma.product.findMany({where:{...where,categoryId:{not:null}},select:{category:true},distinct:["categoryId"],take:8}),prisma.buyingGuide.findMany({where:{...publishedNow(),products:{some:{product:{storeId:store.id,status:"ACTIVE"}}}},include:{author:true,category:true},orderBy:{updatedAt:"desc"},take:6})]);res.json({...store,products:products.map(card),popularCategories:categoryRows.map(x=>x.category).filter(Boolean),relatedGuides:guides,pagination:pagination(page,pageSize,total)})});

app.get("/api/brands",async(_req,res)=>res.json(await prisma.brand.findMany({where:{active:true},orderBy:{name:"asc"}})));
app.get("/api/brands/:slug",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize);const brand:any=await prisma.brand.findFirst({where:{slug:req.params.slug,active:true}});if(!brand)return res.status(404).json({message:"Brand not found"});const where={status:"ACTIVE" as const,brandId:brand.id};const [products,total,guides]=await Promise.all([prisma.product.findMany({where,include:cardInclude(),orderBy:[{featured:"desc"},{updatedAt:"desc"}],skip:(page-1)*pageSize,take:pageSize}),prisma.product.count({where}),prisma.buyingGuide.findMany({where:{...publishedNow(),products:{some:{product:{brandId:brand.id,status:"ACTIVE"}}}},include:{author:true,category:true},orderBy:{updatedAt:"desc"},take:6})]);res.json({...brand,products:products.map(card),relatedGuides:guides,pagination:pagination(page,pageSize,total)})});

app.get("/api/deals",async(_req,res)=>{const rows=await prisma.deal.findMany({where:liveDeal(),include:{product:{include:cardInclude()}},orderBy:{endsAt:"asc"}});res.json(rows.filter(row=>row.product.status==="ACTIVE").map(row=>({...row,product:card(row.product)})))});
app.get("/api/banners",async(_req,res)=>res.json(await prisma.banner.findMany({where:{status:"ACTIVE",AND:[{OR:[{startsAt:null},{startsAt:{lte:new Date()}}]},{OR:[{endsAt:null},{endsAt:{gt:new Date()}}]}]},orderBy:{sortOrder:"asc"}})));

app.get("/api/blog",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize);const where=publishedNow();const [items,total]=await Promise.all([prisma.blogPost.findMany({where,include:{category:true,authorProfile:true},orderBy:{publishedAt:"desc"},skip:(page-1)*pageSize,take:pageSize}),prisma.blogPost.count({where})]);res.json({items,pagination:pagination(page,pageSize,total)})});
app.get("/api/blog/:slug",async(req,res)=>{const post:any=await prisma.blogPost.findFirst({where:{slug:req.params.slug,...publishedNow()},include:{category:true,authorProfile:true,productPlacements:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}},guidePlacements:{where:{guide:publishedNow()},include:{guide:{include:{category:true,author:true}}},orderBy:{sortOrder:"asc"}},commerceCategoryPlacements:{where:{category:{status:"ACTIVE"}},include:{category:true},orderBy:{sortOrder:"asc"}}}});if(!post)return res.status(404).json({message:"Article not found"});res.json({...post,relatedProducts:post.productPlacements.map((x:any)=>card(x.product)),relatedGuides:post.guidePlacements.map((x:any)=>x.guide),relatedCategories:post.commerceCategoryPlacements.map((x:any)=>x.category)})});

app.get("/api/guides",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize),where=publishedNow();const [items,total]=await Promise.all([prisma.buyingGuide.findMany({where,include:{category:true,author:true,products:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}}},orderBy:{updatedAt:"desc"},skip:(page-1)*pageSize,take:pageSize}),prisma.buyingGuide.count({where})]);res.json({items:items.map((g:any)=>({...g,products:g.products.map((x:any)=>card(x.product))})),pagination:pagination(page,pageSize,total)})});
app.get("/api/guides/:slug",async(req,res)=>{const guide:any=await prisma.buyingGuide.findFirst({where:{slug:req.params.slug,...publishedNow()},include:{category:true,author:true,products:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}}}});if(!guide)return res.status(404).json({message:"Guide not found"});const related=await prisma.buyingGuide.findMany({where:{...publishedNow(),id:{not:guide.id},...(guide.categoryId?{categoryId:guide.categoryId}:{})},include:{author:true,category:true},orderBy:{updatedAt:"desc"},take:4});res.json({...guide,products:guide.products.map((x:any)=>card(x.product)),relatedGuides:related})});

app.get("/api/comparisons",async(req,res)=>{const page=pageOf(req.query.page),pageSize=pageSizeOf(req.query.pageSize),where=publishedNow();const [items,total]=await Promise.all([prisma.comparison.findMany({where,include:{author:true,products:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}},stores:{where:{store:{active:true}},include:{store:true},orderBy:{sortOrder:"asc"}}},orderBy:{updatedAt:"desc"},skip:(page-1)*pageSize,take:pageSize}),prisma.comparison.count({where})]);res.json({items:items.map((comparison:any)=>({...comparison,products:comparison.products.map((x:any)=>({...x,product:card(x.product)}))})),pagination:pagination(page,pageSize,total)})});
app.get("/api/comparisons/:slug",async(req,res)=>{const comparison:any=await prisma.comparison.findFirst({where:{slug:req.params.slug,...publishedNow()},include:{author:true,products:{where:{product:{status:"ACTIVE"}},include:{product:{include:cardInclude()}},orderBy:{sortOrder:"asc"}},stores:{where:{store:{active:true}},include:{store:true},orderBy:{sortOrder:"asc"}}}});if(!comparison)return res.status(404).json({message:"Comparison not found"});res.json({...comparison,products:comparison.products.map((x:any)=>card(x.product)),stores:comparison.stores.map((x:any)=>x.store)})});

app.get("/api/authors/:slug",async(req,res)=>{const author=await prisma.author.findFirst({where:{slug:req.params.slug,active:true},include:{posts:{where:publishedNow(),orderBy:{publishedAt:"desc"},take:12},guides:{where:publishedNow(),orderBy:{publishedAt:"desc"},take:12},comparisons:{where:publishedNow(),orderBy:{publishedAt:"desc"},take:12}}});if(!author)return res.status(404).json({message:"Author not found"});const indexableWorkCount=[...author.posts,...author.guides,...author.comparisons].filter(item=>item.robotsIndex).length;res.json({...author,indexableWorkCount})});
app.get("/api/pages/:slug",async(req,res)=>{const page=await prisma.editorialPage.findFirst({where:{slug:req.params.slug,...publishedNow()}});if(!page)return res.status(404).json({message:"Page not found"});res.json(page)});

app.get("/api/seo/manifest",async(_req,res)=>{const [settings,products,categories,stores,brands,guides,posts,comparisons,pages,authors]=await Promise.all([prisma.siteSettings.findUnique({where:{id:"global"}}),prisma.product.findMany({where:{status:"ACTIVE",robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.category.findMany({where:{status:"ACTIVE",robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.store.findMany({where:{active:true,robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.brand.findMany({where:{active:true,robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.buyingGuide.findMany({where:{...publishedNow(),robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.blogPost.findMany({where:{...publishedNow(),robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.comparison.findMany({where:{...publishedNow(),robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.editorialPage.findMany({where:{...publishedNow(),robotsIndex:true},select:{slug:true,updatedAt:true,canonicalUrl:true}}),prisma.author.findMany({where:{active:true,OR:[{posts:{some:{...publishedNow(),robotsIndex:true}}},{guides:{some:{...publishedNow(),robotsIndex:true}}},{comparisons:{some:{...publishedNow(),robotsIndex:true}}}]},select:{slug:true,updatedAt:true}})]);res.json({settings,products,categories,stores,brands,guides,posts,comparisons,pages,authors})});

app.get("/api/homepage",async(_req,res)=>{const rows:any[]=await prisma.homepageSection.findMany({where:{visible:true},orderBy:{sortOrder:"asc"},include:{products:{where:{product:{status:"ACTIVE"}},orderBy:{sortOrder:"asc"},include:{product:{include:homepageCardInclude()}}},categories:{where:{category:{status:"ACTIVE"}},orderBy:{sortOrder:"asc"},include:{category:true}},stores:{where:{store:{active:true}},orderBy:{sortOrder:"asc"},include:{store:true}}}});const [banners,posts]=await Promise.all([prisma.banner.findMany({where:{status:"ACTIVE",AND:[{OR:[{startsAt:null},{startsAt:{lte:new Date()}}]},{OR:[{endsAt:null},{endsAt:{gt:new Date()}}]}]},orderBy:{sortOrder:"asc"}}),rows.some(section=>section.type==="BLOG")?prisma.blogPost.findMany({where:publishedNow(),include:{category:true,authorProfile:true},orderBy:{publishedAt:"desc"},take:8}):[]]);const sections:any[]=rows.map(({products,categories,stores,...section})=>({...section,products:homepageProducts(section.type,products,section.maxItems),categories:categories.slice(0,section.maxItems||undefined).map(({category}:any)=>category),stores:stores.slice(0,section.maxItems||undefined).map(({store}:any)=>store),posts:section.type==="BLOG"?posts.slice(0,section.maxItems||8):undefined}));for(const banner of banners)sections.push({id:`banner-${banner.id}`,type:"PROMO_BANNER",title:banner.title,subtitle:banner.subtitle,background:banner.background,ctaText:banner.buttonLabel,ctaUrl:banner.buttonUrl,sortOrder:banner.sortOrder,config:{image:banner.image,storeLogo:banner.logo}});sections.sort((a,b)=>a.sortOrder-b.sortOrder);res.json({sections})});

const writeLimiter=rateLimit({windowMs:60_000,limit:30});
app.post("/api/newsletter",writeLimiter,async(req,res)=>{const body=z.object({email:z.string().email()}).parse(req.body);res.status(201).json(await prisma.newsletterSubscriber.upsert({where:{email:body.email},create:body,update:{status:"ACTIVE"}}))});
app.post("/api/analytics/affiliate-click",writeLimiter,async(req,res)=>{const body=z.object({productId:z.string().nullable().optional(),productName:z.string().max(200).nullable().optional(),storeId:z.string().nullable().optional(),storeName:z.string().max(120).nullable().optional(),placement:z.enum(["homepage","product","category","guide","search","store","brand","comparison","blog","deals"]),pagePath:z.string().max(500).startsWith("/")}).parse(req.body);await prisma.affiliateClick.create({data:body});res.status(202).json({recorded:true})});

app.use(apiError);
app.listen(Number(process.env.PORT||4000),()=>console.log(`API listening on :${process.env.PORT||4000}`));
